export enum Icon {
    EYE = 'pi pi-eye',
    EYE_SLASH = 'pi pi-eye-slash',
    TIMES = 'pi pi-times',
    HOME = 'pi pi-home',
    CALCULATOR = 'fa fa-calculator',
    CHART = 'pi pi-chart-line',
    TABLE = 'pi pi-table',
    PENCIL = 'pi pi-pencil',
    CUTLERY = 'fa fa-cutlery',
    TRASH = 'pi pi-trash',
    TIMES_CIRCLE = 'pi pi-times-circle',
    USERS = 'pi pi-users',
    CHECK = 'pi pi-check',
}